### ISSUE TITLE
Unknown encoder

### ISSUE THREAD

**Issue by aicortez** [JamesTheHacker/Facebook-Live-Reactions#11]
When I try to run the script it gives me this message:

Unknown encoder 'libfdk aac'

**Comment by essolh** [comment]
Hello Brother how Can you Help me to install this script ?

**Comment by aicortez** [comment]
Take a look at the readme, James did a really good joob explaining everything

**Comment by essolh** [comment]
ok bro

**Comment by JamesTheHacker** [comment]
@janewbz you need to compile `ffmeg` with aac. What OS are you using?

**Comment by essolh** [comment]
Brother James i dont know how can i installit i have host and domaine name and filezilla how can i installed please can i send you info to installed for me please

**Comment by ryanwhittaker** [comment]
Another solution to this if you're having trouble getting ffmpeg to compile with the libfdk_aac library is replacing the `fblive.sh` file with the following:

```
ffmpeg \
-re -y \
-loop 1 \
-f image2 \
-i images/stream.jpg \
-i data/audio-loop.mp3 \
-acodec aac -strict -2 \
-ac 1 \
-ar 44100 \
-b:a 128k \
-vcodec libx264 \
-pix_fmt yuv420p \
-vf scale=640:480 \
-r 30 \
-g 60 \
-f flv \
"..."
```

`ffmpeg` ships with the aac codec which can be used as long as you have the `-strict` and `-2` tags.

**Comment by JamesTheHacker** [comment]
@essolh If you don't have SSH access to your server, or no permissions to install, you need to speak with the hosting provider.

**Comment by aicortez** [comment]
@JamesTheHacker I just ended up using aac. Now I'm getting the following error when running fblive.php:


PHP Warning:  Module 'pthreads' already loaded in Unknown on line 0
PHP Warning:  Module 'pthreads' already loaded in Unknown on line 0
PHP Warning:  Module 'pthreads' already loaded in Unknown on line 0
PHP Warning:  Module 'pthreads' already loaded in Unknown on line 0

Fatal error: Uncaught exception 'Intervention\Image\Exception\NotSupportedException' with message 'GD Library extension not available with this PHP installation.' in /root/Facebook-Live-Reactions/vendor/intervention/image/src/Intervention/Image/Gd/Driver.php:16
Stack trace:
#0 /root/Facebook-Live-Reactions/vendor/intervention/image/src/Intervention/Image/ImageManager.php(107): Intervention\Image\Gd\Driver->__construct()
#1 /root/Facebook-Live-Reactions/vendor/intervention/image/src/Intervention/Image/ImageManager.php(50): Intervention\Image\ImageManager->createDriver()
#2 /root/Facebook-Live-Reactions/vendor/intervention/image/src/Intervention/Image/ImageManagerStatic.php(57): Intervention\Image\ImageManager->make('./images/backgr...')
#3 /root/Facebook-Live-Reactions/fblive.php(23): Intervention\Image\ImageManagerStatic::make('./images/backgr...')
#4 {main}
  thrown in /root/Facebook-Live-Reactions/vendor/intervention/image/src/Intervention/Image/Gd/Driver.php on line 16

Ps: I'm using ubuntu 15.10 btw

**Comment by JamesTheHacker** [comment]
@janewbz You need to install the GD extension. `sudo apt-get install php5-gd` if you're using PHP5.

**Comment by aicortez** [comment]
@JamesTheHacker Thanks. I'm almost done, now I get a **No POST_ID set. Remeber to set it when you go live** even though I copied the post ID and pasted in the settings file

**Comment by JamesTheHacker** [comment]
@janewbz You're the second person with this issue. I'm on the case to get everything tested and fixed this morning. I had a late night with work last night.

**Comment by aicortez** [comment]
@JamesTheHacker take your time, I appreciate your help :)

**Comment by essolh** [comment]
thanks you for the support all thing free is dificult to geit but thanks
you for your help

**Comment by JamesTheHacker** [comment]
There's a branch waiting to be merged. It was updated less than an hour ago. Let me know if you get the same issues please.

**Comment by JamesTheHacker** [comment]
@janewbz the solution to this problem is to install `ffmpeg` with `libfdk-aac`. It does mention that in the docs. Also note you will need to enable `librtmp` too. If you're using OSX this can be done easily with `brew`.
