### ISSUE TITLE
php fblive.php | doesn't work 

### ISSUE THREAD

**Issue by kolmtk** [JamesTheHacker/Facebook-Live-Reactions#12]
Parse error: syntax error, unexpected '[' in /root/facebook-live-reactions/functions.php on line 11

**Comment by mauran** [comment]
You're running an too old PHP-version.

**Comment by kolmtk** [comment]
i try to change it to latest version, i got same error!!!

**Comment by kolmtk** [comment]
can any some help me?

**Comment by JamesTheHacker** [comment]
Very strange. Anyway, this version is going to be replaced with the other branch. I've updated it tonight. Please test it and let me know if it works.

**Comment by kolmtk** [comment]
same problem in this lines:
[27-Nov-2016 14:37:15 UTC] PHP Warning:  array_walk() expects parameter 1 to be array, boolean given in /root/facebook-live-reactions/src/Facebook.php on line 48
[27-Nov-2016 14:37:15 UTC] PHP Warning:  Invalid argument supplied for foreach() in /root/facebook-live-reactions/src/Renderer.php on line 22

**Comment by JamesTheHacker** [comment]
Ok, this looks like you're not getting any reactions from Facebook. I assume you've added the access token, app id and app secret right? Also, the account you create your application on is this the same account that has the page? For some reason you're not getting any reactions from Facebook.

**Comment by kolmtk** [comment]
It's work , Thank you

Just i need to know, how can i add Arabic character in shoutouts, because i got problem when i replace the font with Arabic font.
See the problem in the Attach image.
![untitled](https://cloud.githubusercontent.com/assets/23712852/20652537/f96b91ea-b503-11e6-8fb6-a1efff6f7d7c.jpg)

**Comment by JamesTheHacker** [comment]
I'll look into this after work buddy. Glad that you got it working 👍

**Comment by kolmtk** [comment]
Please i can't used it without Arabic font.. try to help me in this case!

**Comment by kolmtk** [comment]
can you help!!
