### ISSUE TITLE
Problem with stream

### ISSUE THREAD

**Issue by abbbcccaa** [JamesTheHacker/Facebook-Live-Reactions#15]
Hello, when i start stream i am getting information on fb about "stream offline" but packets going, where is problem? ubuntu 16, php7
![chrome_2016-11-26_06-43-22](https://cloud.githubusercontent.com/assets/8458809/20638304/be60d38c-b3a3-11e6-9400-a6237b368f69.jpg)

**Comment by JamesTheHacker** [comment]
1. Are you waiting a few moments for Facebook to load the preview? Depend on how fast your connection is it could take a moment
2. Are you streaming audio? If so what is the audio length?
3. Is the `rtmp://...` URL correct?

**Comment by abbbcccaa** [comment]
1.yes im waiting
2. im streaming audio length 5h
3. rtmp is correct

**Comment by JamesTheHacker** [comment]
Have you tried the recently updated branch?

**Comment by abbbcccaa** [comment]
Could you provide link to the lastest branch?

**Comment by mehh** [comment]
Im having the same issue, and I am using the latest branch

**Comment by mehh** [comment]
- Are you waiting a few moments for Facebook to load the preview? Depend on how fast your connection is it could take a moment
-- **Yes**
- Are you streaming audio? If so what is the audio length?
-- **26 Minutes to test**
- Is the rtmp://... URL correct?
-- **Yes**
- Version
-- **This Branch:** 
-- https://github.com/JamesTheHacker/Facebook-Live-Reactions/tree/added_default_shoutout
<img width="1920" alt="screen shot 2016-11-26 at 11 18 26 pm" src="https://cloud.githubusercontent.com/assets/1928672/20646499/b2994bd4-b42e-11e6-9e9e-fe3d047d9d66.png">

**Comment by abbbcccaa** [comment]
Bump

**Comment by JamesTheHacker** [comment]
Did you install ffmpeg with `librtmp`? To check, run `ffmpeg` at the terminal and look for the following output: 

```
ffmpeg version 3.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.38)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libfdk-aac --enable-libmp3lame --enable-librtmp --enable-libx264 --enable-libx265 --enable-libxvid --enable-opencl --disable-lzma --enable-nonfree --enable-vda
```

Notice: `--enable-librtmp`

I didn't see it in your output @mehh. Could you also check @lanceq1337.

**Comment by eirisdg** [comment]
Same issue here. ffmpeg compiled from sources.

> ffmpeg version N-82659-g9478bd8 Copyright (c) 2000-2016 the FFmpeg developers
>   built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
>   configuration: --enable-gpl --enable-libx264 --enable-libmp3lame --enable-nonfree --enable-libfdk-aac --enable-librtmp
>   libavutil      55. 41.101 / 55. 41.101
>   libavcodec     57. 66.108 / 57. 66.108
>   libavformat    57. 58.101 / 57. 58.101
>   libavdevice    57.  2.100 / 57.  2.100
>   libavfilter     6. 67.100 /  6. 67.100
>   libswscale      4.  3.101 /  4.  3.101
>   libswresample   2.  4.100 /  2.  4.100
>   libpostproc    54.  2.100 / 54.  2.100
> Hyper fast Audio and Video encoder
> usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**Comment by abbbcccaa** [comment]
@JamesTheHacker with the latest version stream working, but when im turning on 
~/facebook-live-reactions# php fblive.php
reactions and share not updating still 0 everywhere, how to debug this? no errors in phplog and apachelog

**Comment by eirisdg** [comment]
With librtmp installed not working on Ubuntu 16.04

I've compiled from sources ffmpeg:

> ffmpeg version N-82660-gd9883de Copyright (c) 2000-2016 the FFmpeg developers
>   built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
>   configuration: --enable-gpl --enable-libx264 --enable-libmp3lame --enable-nonfree --enable-libfdk-aac --enable-librtmp
>   libavutil      55. 41.101 / 55. 41.101
>   libavcodec     57. 66.108 / 57. 66.108
>   libavformat    57. 58.101 / 57. 58.101
>   libavdevice    57.  2.100 / 57.  2.100
>   libavfilter     6. 67.100 /  6. 67.100
>   libswscale      4.  3.101 /  4.  3.101
>   libswresample   2.  4.100 /  2.  4.100
>   libpostproc    54.  2.100 / 54.  2.100
> Hyper fast Audio and Video encoder

I create the stream but in Facebook, no conection.

**Comment by mehh** [comment]
I just ran:

`brew install rtmpdump`
`brew install ffmpeg --with-x265 --with-rtmpdump  --with-fdk-aac`

and it works!  Great!

**Comment by eirisdg** [comment]
Wich is your 'ffmpeg' command output?

**Comment by mehh** [comment]
```
ffmpeg version 3.2.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 7.0.2 (clang-700.1.81)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.2.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libfdk-aac --enable-libmp3lame --enable-librtmp --enable-libx264 --enable-libx265 --enable-libxvid --enable-opencl --disable-lzma --enable-nonfree --enable-vda
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

**Comment by TeorikDeli** [comment]
I have the same problem. Probably because I couldn't compile the ffmpeg with librtmp (on CentOS 7.2). This is the configuration error:

"ERROR: librtmp not found using pkg-config"

but "/usr/local/lib/pkgconfig/" is containing "librtmp.pc" file and "rtmpdump" command is working.

Am I missing something? I couldn't find any good articles to compile with librtmp on CentOS.

I also tried with "yum ffmpeg ffmpeg-devel" but no luck.

**Comment by TeorikDeli** [comment]
I just solved the same problem with using a flash supported browser -_- It seems, facebook requires adobe flash to start (and watch) live streaming.
