### ISSUE TITLE
Problem with stream - ends with "This live video has ended."

### ISSUE THREAD

**Issue by JakubKontra** [JamesTheHacker/Facebook-Live-Reactions#16]
When i start i got this

Codec AVOption b (set bitrate (in bits/s)) specified for output file #0 (rtmp://rtmp-api.facebook.com:80/rtmp/1130523197002349?ds=1&s_l=1&a=AaZ4MldB-BHc7tzI) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
[scale @ 0x1c46b80] The <w>:<h>:flags=<flags> option syntax is deprecated. Use either <w>:<h>:<flags> or w=<w>:h=<h>:flags=<flags>.

And stream stops? i dont know, when i react to the post it will change the picture but overlay is visible.

**Comment by JamesTheHacker** [comment]
1. What version of `ffmpeg` are you using?
2. Could you post the entire output

**Comment by JakubKontra** [comment]
1) the latest...

2) maybe there is a problem with music.. i remove it.. and facebook need it (stream is long as mp3 )
