### ISSUE TITLE
Problem fblive.php

### ISSUE THREAD

**Issue by damko123** [JamesTheHacker/Facebook-Live-Reactions#17]
PHP Fatal error:  Uncaught Error: Class 'FBReactions\Facebook' not found in /facebook-live-reactions/fblive.php:26
Stack trace:
#0 {main}
  thrown in /facebook-live-reactions/fblive.php on line 26

**Comment by JamesTheHacker** [comment]
Did you run `php composer.phar install`?

**Comment by damko123** [comment]
when i run php composer.phar install i get this error : 


  [Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 5:
  ...image": "^2.3",    },    "autoload": {
  ---------------------^
  Expected: 'STRING' - It appears you have an extra trailing comma

**Comment by JamesTheHacker** [comment]
Pull the repo and try again. Should work.
