### ISSUE TITLE
The Video not collect all Reactions

### ISSUE THREAD

**Issue by kolmtk** [JamesTheHacker/Facebook-Live-Reactions#20]
As you know we have more than the "public result" from every post..
some time you see the Reactions = 500
but we have more than that.. We have 200 too from share ..
you can found that from "Publishing Tools" Tab in Facebook.
can we collect this numbers too ?

Thank you

**Comment by JamesTheHacker** [comment]
Currently the script does not count the reactions from shared posts. I will look into including this.

**Comment by kolmtk** [comment]
I know but this it's very very important , you can Distinct from others script if you do this option.

**Comment by kolmtk** [comment]
Look in this result .. more than the half reactions from the share.
![untitled](https://cloud.githubusercontent.com/assets/23712852/20751870/eb45bf0a-b706-11e6-91b9-2d4434dbc5e6.png)

**Comment by JamesTheHacker** [comment]
Ok, I will build it in if Facebook's API returns those stats.

**Comment by kolmtk** [comment]
Thank you.

**Comment by kolmtk** [comment]
Hello,

Please if you help me in this option Asap.

Best Regard's

**Comment by kolmtk** [comment]
Hello,

Please if you help me in this option Asap.

Best Regard's

**Comment by JamesTheHacker** [comment]
Hi, please give me some time. I am unable to make any changes until the weekend as I am busy with work and family commitments. If it's possible I will implement it.

**Comment by kolmtk** [comment]
Thank you very much, take your time.

**Comment by kolmtk** [comment]
We Hope you still remember us. ;)

**Comment by kolmtk** [comment]
We Hope you still remember us. ;)

**Comment by kolmtk** [comment]
Any update bro?

**Comment by kolmtk** [comment]
Did you can ?

**Comment by teamcoltra** [comment]
@kolmtk  - It's not polite to harass someone about open source software. He will build a feature if he can and has the time. If you are in a rush you can help all of us out by hiring someone to add the feature into the code and submit a pull request.
