### ISSUE TITLE
Error when running "php fblive.php"

### ISSUE THREAD

**Issue by drewdeakin** [JamesTheHacker/Facebook-Live-Reactions#22]
I get the following error everytime I run "php fblive.php"

`PHP Fatal error:  Class 'FBReactions\Facebook' not found in /var/www/html/live/fblive.php on line 26`

**Comment by drewdeakin** [comment]
Just updated my php to 7 (as I was running 5.9 heh)

And I'm getting the same error;


```
PHP Fatal error:  Uncaught Error: Class 'FBReactions\Facebook' not found in /var/www/html/live/fblive.php:26
Stack trace:
#0 {main}
  thrown in /var/www/html/live/fblive.php on line 26
```

**Comment by JamesTheHacker** [comment]
Have you ran `composer install` ?
