### ISSUE TITLE
Streaming aborts  after ~30-60 minutes

### ISSUE THREAD

**Issue by h1rule** [JamesTheHacker/Facebook-Live-Reactions#23]
Hello,

my stream is aborting after 30-60 minutes, even when i have a 4 hours musicfile.

**Comment by kolmtk** [comment]
me too ..

**Comment by JamesTheHacker** [comment]
Ok looking into this. I've just set up a stream and let it run for a while to see if I can replicate.

**Comment by kolmtk** [comment]
You still looking ?! :)

**Comment by abdusfauzi** [comment]
@JamesTheHacker how was the run? 👌🏻

**Comment by JamesTheHacker** [comment]
Sorry guys I've been super busy. I've lost 2 family members since January and have a tonne of work to deal with. If anyone can replicate the issue I will happily look into it, but I'm unable to replicate. I've had a server running for over a month with no issues. It's likely an edge case.

**Comment by abdusfauzi** [comment]
@JamesTheHacker condolence :(
