### ISSUE TITLE
Can this be used on live streams from personal profiles?

### ISSUE THREAD

**Issue by pseudokool** [JamesTheHacker/Facebook-Live-Reactions#24]
This works great on Pages, would I be right in assuming that this wont be usable on a live stream from a personal profile (especially since I don't think such a stream is possible from the web)

**Comment by JamesTheHacker** [comment]
I haven't tested it on personal accounts. So long as you have a stream key I can't see why it wouldn't work. Just add your profile ID to `pageID` and the ID of your livestream post to `postID`.
