### ISSUE TITLE
how i make this scripte work in my web site 

### ISSUE THREAD

**Issue by youssefm199** [JamesTheHacker/Facebook-Live-Reactions#25]
how i make this scripte work in my web site  
is this scripte like this 
http://esuite.me/facebook-live-direct-sellers/

**Comment by JamesTheHacker** [comment]
The script is not built to work with OBS Studio. It's meant to run at the command line or on a server.

I do provide OBS Studio templates, but these are commercial services. If you're interested in this shoot me an email: jameslovescode@gmail.com
