### ISSUE TITLE
Sox Installation error in Centos 7

### ISSUE THREAD

**Issue by sardarsaab** [JamesTheHacker/Facebook-Live-Reactions#26]
Hi,

I tried to install Sox in centos 7. I searched in google and installed it. But now when i tried to run Sox command to make loop (sox audio.mp3 audio-loop.mp3 repeat 15) I got error 
-bash: sox: command not found

Can you please help me.

**Comment by JamesTheHacker** [comment]
Did you resolve this? If you've installed `sox` from your OS's repo's it should work fine. Maybe the path is missing?
