### ISSUE TITLE
Are Reactions cumulative ?

### ISSUE THREAD

**Issue by omarojo** [JamesTheHacker/Facebook-Live-Reactions#27]
I noticed that when I do a LOVE reaction the love totalcount increases +1, but if then I do a WOW reaction. The LOVE totalcount will decrease -1 and WOW totalcount will increase.

So it seems that the reactions are unique... doesnt matter if you click the LOVE reaction many many times. right ???

**Comment by JamesTheHacker** [comment]
This is normal behaviour. If you change your reaction it will change in the live stream.
