### ISSUE TITLE
Functions.php should read settings and build reactions + positions by default

### ISSUE THREAD

**Issue by ryanwhittaker** [JamesTheHacker/Facebook-Live-Reactions#3]
Functions.php should read the settings and build the reactions in `drawReactionCount` automatically. We can also use the image's width in pixels divided by the number of active reactions to properly space the reactions on the screen by default (which can still be overwritten through settings). This should allow further customization of the live image.

**Comment by JamesTheHacker** [comment]
> Functions.php should read the settings and build the reactions in drawReactionCount automatically.

I'm not sure about this. I think each function should be independent to allow for for different settings to be passed in if required. For example the user could pass in a different image, or settings. I do feel it needs some improvement though.

> We can also use the image's width in pixels divided by the number of active reactions to properly space the reactions on the screen by default (which can still be overwritten through settings). This should allow further customization of the live image.

I agree with this though. You're right. I can do this tomorrow evening, or you can submit a pull request and I will happily merge.
