### ISSUE TITLE
Questionmark image

### ISSUE THREAD

**Issue by pimbolilu** [JamesTheHacker/Facebook-Live-Reactions#7]
Hello,

first thank you for the script :)

I have 2 issues:

- As you can see I got a bit image overlay with a questionmark (how can I solve this?)
![untitled](https://cloud.githubusercontent.com/assets/19839434/20533012/54248a5a-b0dc-11e6-89fe-fd2a56af0404.png)

- It does now displays my Likes and shouts. (how can I solve this?)

Is it related to this error:
PHP Warning:  array_filter() expects parameter 1 to be array, null given in /home/ubuntu/Facebook-Live-Reactions/fblive.php on line 57

thank you.

**Comment by ryanwhittaker** [comment]
The image with a question mark will appear if no one has commented "share" yet. There does seem to be an issue with scaling on it though, will look into that. 

It should be returning 0s for all the reactions even if there isn't any. Have you updated the POST_ID in the `settings.php` file?

**Comment by JamesTheHacker** [comment]
Ah, yes that question mark image is a problem. I will fix this tonight.

Regarding the empty reaction counts @ryanwhittaker is correct you need to update the `POST_ID` in `settings.php` after you press "Go Live".

**Comment by JamesTheHacker** [comment]
@ryanwhittaker to solve the user image issue I was thinking maybe wrap `drawShoutout` in an `if` block checking to see whether `count($latestShareComment) > 0`. If there are no comments it will just skip drawing the shoutout?

**Comment by ryanwhittaker** [comment]
@JamesTheHacker It looks a little empty/weird if there's no shoutout but there is the shoutout bar imo. It's probably better to get a Facebook/Twitter egg image and just use template text of John Doe or something. 

But we definitely should wrap it in an if block since if we know there are no comments still. It's just wasting speed running through it when it doesn't need to.

**Comment by JamesTheHacker** [comment]
Ah, good point.

**Comment by JamesTheHacker** [comment]
@ryanwhittaker my bad, there's already an `if` block that checks whether an image needs to be downloaded `if ($latestShareComment !== null)`. So I think the only thing left to do is modify the default `profile.jpg` and add a default John Doe shoutout for cases when no comments are found.

**Comment by JamesTheHacker** [comment]
#8 - Added default shoutout. Added error checking.

**Comment by JamesTheHacker** [comment]
{JamesTheHacker}/{Facebook-Live-Reactions}#{8}

**Comment by pimbolilu** [comment]
Hello,

I checked out the latest version and it seems that the questionmark problem is solved now,
but I still get no likes and shouts.

I changed the post id to the value which I found in this link:

https://www.facebook.com/XXXXXX/videos/347968685570152/

What elso could be the problem?

**Comment by ryanwhittaker** [comment]
@pimbolilu Try testing by using the Graph API, as thats what is used to pull share data in the repo. 

1. Go here: https://developers.facebook.com/tools/explorer/
2. In the top right drop down next to Application that currently has `Graph API Explorer` selected. Click and select the Facebook Application you created.
3. Paste the following request in the query: `POST_ID/comments?filter=stream&order=reverse_chronological` . 
4. Also check this request in the query: `?ids=POST_ID&fields=reactions.type(LIKE).limit(0).summary(total_count).as(LIKE),reactions.type(HAHA).limit(0).summary(total_count).as(LOVE),reactions.type(LOVE).limit(0).summary(total_count).as(HAHA),reactions.type(WOW).limit(0).summary(total_count).as(WOW)`

Replace POST_ID with your Post ID. Do your comments from the video appear there? 

If you can't complete any of these steps (such as the Application part), it means you still need to do something, so refer back to Installation in the READme.

Let me know if you follow those steps and your comments come back fine in the request.

**Comment by JamesTheHacker** [comment]
@pimbolilu did you resolve this issue. There's a new version waiting to be merged. Try it please. If you get an issue file a new issue.
